# -*- coding: utf-8 -*-
"""Introdução data science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17hhqoPoTsP1xi6xA3ZXKVQ6BBl-QD9I0
"""

import pandas as pd

notas = pd.read_csv("ratings.csv")

notas.columns = ["usuarioId","filmeId","nota","momento"]
notas.head()

"""#Analisando notas no geral"""

notas['nota']

notas['nota'].unique()

notas['nota'].value_counts()

print("Media",notas['nota'].mean())
print("Mediana",notas.nota.median())

notas.nota.plot(kind="hist")

notas.nota.describe()

import seaborn as sns

sns.boxplot(notas.nota)

"""#Analisando os Filmes"""

filmes = pd.read_csv("movies.csv")
filmes.columns = ["filmeId","titulo","genero"]
filmes.head()

"""#Analisando algumas notas especificas por filme"""

notas.query("filmeId==1").nota.mean()

"""#Medias agrupadas por nota"""

medias_por_filme = notas.groupby("filmeId").mean().nota
medias_por_filme.head()

medias_por_filme.plot(kind="hist")

sns.boxplot(medias_por_filme)

medias_por_filme.describe()

sns.distplot(medias_por_filme, bins=10)

import matplotlib.pyplot as plt

plt.hist(medias_por_filme)
plt.title("Histograma dos filmes")

tmdb = pd.read_csv("tmdb_5000_movies.csv")
tmdb.head()

tmdb.original_language.unique() #variavel categorica nominal

#primeiro grau
#segundo grau
#terceiro grau
#1 grau < 2 grau < 3 grau #categorica ordinal

#budget => orcamento => quantitativa continua

contagem_de_lingua = tmdb["original_language"].value_counts().to_frame().reset_index()
contagem_de_lingua.columns = ["original_language","total"]
contagem_de_lingua.head()

sns.barplot(x= "original_language",y="total",data = contagem_de_lingua)

sns.catplot(x="original_language",kind="count",data=tmdb)

plt.pie(contagem_de_lingua["total"], labels = contagem_de_lingua["original_language"])

total_por_lingua = tmdb["original_language"].value_counts()
total_geral = total_por_lingua.sum()
total_de_ingles = total_por_lingua.loc["en"]
total_do_resto = total_geral - total_de_ingles
print(total_de_ingles, total_do_resto)

dados = {
    'lingua' : ['ingles','outros'],
    'total' : [total_de_ingles, total_do_resto]

}

dados = pd.DataFrame(dados)
dados

sns.barplot(data = dados, x = 'lingua', y = 'total')

plt.pie(dados["total"], labels = dados["lingua"])

total_por_lingua_de_outros_filmes = tmdb.query("original_language != 'en'").original_language.value_counts()
total_por_lingua_de_outros_filmes.head()

filmes_sem_lingua_original_ingles = tmdb.query("original_language != 'en'")
sns.catplot(x="original_language",
            kind="count",aspect=2,
            data=filmes_sem_lingua_original_ingles,
            palette="GnBu_d",
            order =total_por_lingua_de_outros_filmes.index )